### ISSUE TITLE
Unable to find the css file in blazor WebAssembly 3.2.0 Preview 1

### ISSUE THREAD

**Issue by nagtilaklaxman** [Blazored/Toast#51]
I am using Blazored.Toast in my webassembly Project.
I have referenced the css in index.html as below.
<link href="_content/Blazored.Toast/blazored-toast.css" rel="stylesheet" />

Before updating to WebAssembly 3.2.0 Preview 1 it was working but after updating the blazor to WebAssembly 3.2.0 Preview 1  it is not working .
issue is Css file is not found at the path.

**Comment by chrissainty** [comment]
I've just created a new Blazor WebAssembly app and added the package and everything has worked as expected.

Have you tried clearing your browser cache, uninstalling and reinstalling the package?

**Comment by nagtilaklaxman** [comment]
Yes. I have tried clearing the browser cache and reinstalling the package. but no success.
**_content** folder is not getting created in **dist folde**r for **netstandard2.1** on my system. 
It was used to get created for **netstandard2.0**. 
You can see  my attached screenshots.
![DotNetStandard2 1](https://user-images.githubusercontent.com/16507190/74803566-7cc4da00-5331-11ea-91d4-d452e95b7440.PNG)
![dotNetStandard2 0](https://user-images.githubusercontent.com/16507190/74803568-7d5d7080-5331-11ea-84b8-8a8d0c3716c9.PNG)

**Comment by chrissainty** [comment]
I think this could be down to the fact I haven't rebuilt the project against the latest .NET Core Preview. I'll try and get that done today.

**Comment by chrissainty** [comment]
@nagtilaklaxman I've just pushed a new version of the package. Please let me know if it resolves your issue.

**Comment by nagtilaklaxman** [comment]
Thank you chris for instant support. But still my issue is not resolved.
you can check the attached screenshots.
![client project file](https://user-images.githubusercontent.com/16507190/74907848-5b82ed00-5408-11ea-85f1-98b876946ab5.PNG)
![DotNetStandard2 1](https://user-images.githubusercontent.com/16507190/74907850-5cb41a00-5408-11ea-81b7-7c82fc229def.PNG)
![toaster404](https://user-images.githubusercontent.com/16507190/74907851-5cb41a00-5408-11ea-9fd4-402c6b451ca9.PNG)

**Comment by chrissainty** [comment]
I've doubled checked this with a couple of projects my end with 3 separate machines and everything is working as expected. So it seems like this issue is local to you, unfortunately.

Could you try creating a brand new Blazor project installing the packages and seeing if that works?

**Comment by nagtilaklaxman** [comment]
Thank you very much Chris for your help.  
I tried on new project and it is working fine .
I need to debug and find the issue in my project.

**Comment by esamk** [comment]
Hi Chris
I've got the same problem. Toasts work but not with the styles. 



I've cleaned and rebuilt my project as well as re-installed the nuget package several times and
situation remains the same.

**Comment by chrissainty** [comment]
Hi @esamk, sorry to hear you're having issues. I'm definitely open to the possibility that there could be a bug, but at the moment I think it's more likely that you have a local issue. As I said previously, could you create a new project and add the package and see if you get the same issue?

So far anyone who's had this issue or something similar hasn't been able to replicate it, hence my feeling these have been local issues. But if you can manage to create a repro of the problem then that would be awesome and we would have something we can work on.

**Comment by esamk** [comment]
Hi Chris
A clean project works fine, just as you said. 

In my real app I am using Blazorise.Bootstrap, your Typeahead component and a few others.
I'll try to add these one by one to the clean test project to see if anything breaks.

**Comment by JonBrownBOP** [comment]
I was having the same problem, but I realized that [BlazorStrap ](https://blazorstrap.io/V5/V5/components/toast)has Toast built in. I know it is a special case, but trying to save someone else some time troubleshooting.

`<BSToast Color="BSColor.Success" HasIcon="true">
    <Header><strong>BlazorStarp</strong></Header>
    <Content>Hello, world!</Content>
</BSToast>`
